# Generated by Django 5.2.10 on 2026-01-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('target_url', models.URLField(help_text='请输入要抓取的网站地址', verbose_name='目标URL')),
                ('spider_config', models.JSONField(blank=True, default=dict, null=True, verbose_name='爬虫配置')),
                ('frequency', models.CharField(default='daily', max_length=50, verbose_name='抓取频率')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '运行中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='当前状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '爬虫任务',
                'verbose_name_plural': '爬虫任务',
                'db_table': 'spider_task',
            },
        ),
    ]
