# Generated by Django 5.2.10 on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spidertask',
            name='spider_config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='爬虫配置'),
        ),
    ]
