# Generated by Django 5.2.10 on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_spidertask_spider_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='职位名称')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='薪资范围')),
                ('company', models.CharField(max_length=255, verbose_name='公司名称')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作地点')),
                ('source_website', models.CharField(choices=[('boss', 'BOSS直聘'), ('51job', '前程无忧'), ('shixiseng', '实习僧'), ('yingjiesheng', '应届生求职网'), ('lagou', '拉勾网')], default='unknown', max_length=50, verbose_name='来源平台')),
                ('detail_url', models.URLField(unique=True, verbose_name='详情页URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
