# Generated by Django 5.2.10 on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': '职位信息', 'verbose_name_plural': '职位信息'},
        ),
        migrations.AddField(
            model_name='job',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='公司规模'),
        ),
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学历要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='经验要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属行业'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='职位描述'),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='技能标签'),
        ),
        migrations.AddField(
            model_name='job',
            name='welfare',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='福利待遇'),
        ),
    ]
