# Generated by Django 5.2.10 on 2026-02-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_job_options_job_company_size_job_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source_website',
            field=models.CharField(choices=[('boss', 'BOSS直聘'), ('51job', '前程无忧'), ('shixiseng', '实习僧'), ('yingjiesheng', '应届生求职网'), ('lagou', '拉勾网')], default='unknown', max_length=50, verbose_name='来源平台'),
        ),
    ]
